proj_futsal/proj_futsal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scheduler/', include('scheduler.urls')),
]

proj_futsal/scheduler/urls.py
from django.urls import path
from . import views

app_name = 'scheduler'
urlpatterns = [
    path('home', views.home, name = 'home'),
    path('event/<int:pk>/', views.event, name='event'),
    path('register', views.register, name='register'),
    path('edit/<int:pk>/', views.EditPlayer.as_view(), name='edit'),
	path('delete/<int:pk>/', views.DeletePlayer.as_view(), name='delete'),
]

print('loaded urls')

proj_futsal/scheduler/models.py
# Create your models here.
from django.db import models
import datetime

class Event(models.Model):
    class EventStatus(models.TextChoices):
        CONFIRMED = 'CO', 'Confirmed'
        UNCONFIRMED = 'UC', 'Unconfirmed'
        CANCELLED = 'CA', 'Cancelled'
    event_name = models.CharField(max_length=200)
    event_date = models.DateField(default = datetime.datetime.today())
    event_start = models.TimeField(default = datetime.datetime.now())
    event_end = models.TimeField(default = datetime.datetime.now())
    event_created = models.DateTimeField(auto_now_add=True)
    event_updated = models.DateTimeField(auto_now=True)
    event_comment = models.TextField()
    event_status = models.CharField(max_length = 2, choices = EventStatus.choices)

    class Meta:
        ordering = ['event_date', 'event_start']
    def __str__(self):
        return str(self.id)


class Player(models.Model):
    class PlayerStatus(models.TextChoices):
        PLAYER = 'PL', 'Player'
        WATCHING = 'WA', 'Watching'
    class AttendanceStatus(models.TextChoices):
        CONFIRMED = 'CO', 'Confirmed'
        MAYBE = 'MB', 'Maybe'
        WILL_NOT_ATTEND = 'NO', 'Will not attend'
    event = models.ForeignKey(Event, on_delete = models.CASCADE, related_name = 'relevant_event_name')
    name = models.CharField(max_length=200)
    player_status = models.CharField(max_length = 2, choices= PlayerStatus.choices)
    attendance_status = models.CharField(max_length = 2, choices= AttendanceStatus.choices)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    comment = models.TextField(null=True, blank=True)
    class Meta:
        ordering = ['created']
    def __str__(self):
        return self.name

proj_futsal/scheduler/forms.py
from django import forms
from .models import Player


class RegisterPlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['event', 
        'name', 
        'player_status', 
        'attendance_status', 
        'comment',] 

class EditPlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['event', 
        'name', 
        'player_status', 
        'attendance_status', 
        'comment',]  
    

proj_futsal/scheduler/views.py
from django.shortcuts import render
from .models import Player, Event
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from .forms import RegisterPlayerForm, EditPlayerForm
import datetime 
from django.db.models.expressions import RawSQL
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy, reverse


def home(request):
    events = Event.objects.all()
    params = {'eventlist': events}
    return render(request, 'scheduler/home.html', params)

def event(request, pk): 
    dateformat = "%y/%m/%d"
    timeformat = "%H:%M"
    thisEvent=Event.objects.filter(id = pk).values()[0]
    event_name = thisEvent['event_name']
    event_date = datetime.datetime.strftime(thisEvent['event_date'], dateformat)
    event_start = datetime.time.strftime(thisEvent['event_start'], timeformat)
    event_end = datetime.time.strftime(thisEvent['event_end'], timeformat)
    event_comment = thisEvent['event_comment']
    event_status = thisEvent['event_status']

    params = {
        'event_count': Player.objects.filter(event=pk).filter(attendance_status = 'CO').count(),
        'event_name':event_name,
        'event_date':event_date,
        'event_start': event_start,
        'event_end': event_end,
        'event_comment':event_comment,
        'event_status':event_status,
        'players' : Player.objects.filter(event = pk).annotate(N=RawSQL('row_number() over ()', [])).values(),
        'form' : RegisterPlayerForm(initial={'event':pk}),
        }
    return render(request, 'scheduler/event.html', params)

def register(request):
    if request.method == 'POST':
        form = RegisterPlayerForm(request.POST)
        if form.is_valid():
            form.save()
        key = request.POST['event']
    else:
        print('something went wrong')
             
    return redirect(f'event/'+key+'/')

class EditPlayer(UpdateView):
    model = Player
    form_class = EditPlayerForm
    template_name = 'scheduler/edit_player_template.html'

    def get_success_url(self, **kwargs):
        event_key = self.request.POST['event']
        return ('/scheduler/event/'+event_key+'/')

class DeletePlayer(DeleteView):
    model = Player
    template_name = 'scheduler/confirmDelete.html'

    def get_success_url(self, **kwargs):
        event_key = self.request.POST['event']
        return ('/scheduler/event/'+event_key+'/')

    
    

proj_futsal/scheduler/templates/edit_player_template.html
<form id="editform" action="" method="POST">
    {% csrf_token %}
    <div class="modal-body">
    {{form.as_p}}
    <input type="hidden" id="id" name="id" value={{event_key}}>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="submit">Save changes</button>
    </div>
</form> 

proj_futsal/scheduler/templates/scheduler/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8", name="viewport" content="width=device-width, initial-scale=1" >
  <title>scheduler</title>
  <link rel="stylesheet" href="{% static 'scheduler/bootstrap/css/bootstrap.min.css' %}" >
</head>

<body>
  <div class="container"></div>
    <nav class="navbar navbar-light navbar-expand-md navbar-fixed-top navigation-clean-button" style="background: rgb(34, 34, 34);border-radius: 20;border-top-left-radius: 20;border-top-right-radius: 20;border-bottom-right-radius: 20;border-bottom-left-radius: 20;border-style: none;padding-top: 0;padding-bottom: 10px;">
        <div class="container"><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div><a class="navbar-brand" href="#" ><span style="color:white; margin-left:0px;">Futsal Scheduler </span></a></div>
            <div id="navcol-1" class="collapse navbar-collapse" style="color: rgb(255,255,255);">
                <ul class="navbar-nav nav-right">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'scheduler:home' %}" style="color: rgba(224,217,217,0.9);">home </a></li>
                </ul>
            </div>
        </div>
    </nav>
      {% block content %} {% endblock %}
    <footer id="footer" style="width:100">
        <div style="background: black;text-align: center;margin: 0px; padding: 10px;"> 
            <p style="color: grey;">Copyright (c) 2022 facility dev</p>
        </div>
    </footer>
  </div>
  </body>
  <script src="{% static 'scheduler/bootstrap/js/bootstrap.min.js' %}"></script>
</html>

proj_futsal/scheduler/templates/scheduler/confirmDelete.html
{% extends 'scheduler/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}

	<h3>Are you sure you want to delete "{{ object }}"?</h3>
	<input type="hidden" name="event" value="{{ object.event }}">
	<button class="btn btn-primary" type="submit">Confirm</button>


</form>

{% endblock %}

proj_futsal/scheduler/templates/scheduler/edit_player_template.html
{% extends 'scheduler/base.html' %}

{% block content %}

<form id="editform" action="" method="POST">
    {% csrf_token %}
    <div class="modal-body">
    {{form.as_p}}
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" type="submit">Save changes</button>
		<a href="/scheduler/delete/{{player.id}}/" class="btn btn-primary" type="button">Delete</a>
    </div>
</form> 

{% endblock %}

proj_futsal/scheduler/templates/scheduler/event.html
{% extends 'scheduler/base.html' %}

{% block content %}

<div class="container">
    <div>
        <div>
            <h2>{{event_name}}</h2>
            <h3>{{event_date}} {{event_start}} ~ {{event_end}}</h3>
            <p>{{event_comment}}</p>
        </div>
        
            
            <div class="modal" tabindex="-1" id="modalregistration">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Register for event {{event_name}}</h5>

                    </div>
                    <form id="registerform" action="{% url 'scheduler:register' %}" method="POST">
                        {% csrf_token %}
                        <div class="modal-body">
                        {{form.as_p}}
                        <input type="hidden" id="id" name="id" value={{event_key}}>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </form> 
                  </div>
                </div>
            </div>
              


    </div>


    <div class="table-responsive">
        <h4>Current Confirmed: {{event_count}}</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Name</th>
                    <th>Attend?</th>
                    <th>Player?</th>
					<th></th>
                </tr>
            </thead>
            <tbody>
                {% for player in players %}
                <tr>
                    <td>{{player.N}}</td>
                    <td>{{player.name}}</td>
                    <td>{{player.get_attendance_status_display}}</td>
                    <td>{{player.get_player_status_display}}</td>
                    <td><a href="/scheduler/edit/{{player.id}}/" class="btn btn-primary btn-lg" type="button">Edit/Delete</a></div>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div><a class="btn btn-primary btn-lg" type="button" data-bs-toggle="modal" data-bs-target="#modalregistration" id="{{player.pk}}">Register</a></div>
    <br>
</div>
<script>
    $(function(){
       $('#registerform').on('submit', function(e){
            e.preventDefault();
            $.ajax({
                url: "{% url 'scheduler:register' %}",
                type: "POST",
                data: $("registerform").serialize(),
                success: function(data){
                    alert("Successfully submitted.")
                }
            });
       }); 
    });
</script>



{% endblock %}

proj_futsal/scheduler/templates/scheduler/home.html
{% extends 'scheduler/base.html' %}

{% block content %}
<div class="container">
    <div class="table-responsive">
        <table class="table">
        {% for item in eventlist %}
            <tr>
                <td><a href="/scheduler/event/{{item.id}}">{{item.event_name}}</a></td>
                <td>{{ item.event_date|date:'Y/M/d' }}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
</div>
{% endblock %}